version: "3"

tasks:
  build:
    desc: Build Go + Objective-C app
    cmds:
      - rm -rf ./go_app/bin ./bin && mkdir ./go_app/bin  ./bin
      - go build -buildmode=c-archive -o ./bin/golib.a ./go_app/main.go
      - cp ./go_app/libplayer.h ./bin
      - clang -fobjc-arc main.m player_controls.m bin/golib.a  -framework Cocoa -framework AVKit -framework AVFoundation -o VideoPlayer

  run:
    desc: Run app
    cmds:
      - ./go_app/bin/viewbudy
